practice_article/urls.py
from django.urls import path
from . import views


app_name = 'practice_article'


urlpatterns = [
    path('',views.index , name= 'index'),
    path('<int:id>/',views.detail, name= 'detail'),
    path('<int:id>/delete/',views.delete, name='delete'),
    path('new/',views.new, name='new'),
    path('create/',views.create, name='create'),
    path('<int:id>/edit/',views.edit, name='edit'),
    path('<int:id>/update/',views.update, name='update')

]

practice_board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('practice_article/',include('practice_article.urls')),
]

practice_article/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()    
    created_at = models.DateTimeField(auto_now_add=True)

practice_article/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.

def index(request):
    
    articles = Article.objects.all()

    context = {
        'practice_article': articles
    }

    return render (request, 'index.html',context)


def detail(request,id):
    article = Article.objects.get(id=id)


    context = {
        'article': article,
    }

    return render(request,'detail.html',context)

def delete(request, id):
    article = Article.objects.get(id=id)

    article.delete()

    return redirect('practice_article:index')


def new(request):
    return render(request,'new.html')

def create(request):
    title = request.POST.get('title')

    content = request.POST.get('content')

    article = Article()
    article.title = title
    article.content = content
    article.save()

    return redirect('practice_article:detail' ,id=article.id)


def edit(request,id):
    article = Article.objects.get(id=id)

    context = {
        'article' : article
    }

    return render (request,'edit.html',context)
p
def update(request,id):

    title = request.POST.get('title')

    content = request.POST.get('content')


    article = Article.objects.get(id=id)

    article.title = title
    article.content = content
    article.save()

    return redirect('practice_article:detail',id=article.id)

practice_article/templates/detail.html
{% extends 'base.html' %}


{% block body %}

<div class="card">
    <div class="card-header">{{article.title}}</div>
    <div class="card-body">{{article.content}}</div>
    <div class="card-footer">
        <p>{{article.created_at}}</p>
        <a href="{% url 'practice_article:delete' id=article.id %}" class="btn btn-danger">delete</a>
        <a href="{% url 'practice_article:edit' id=article.id %}" class = "btn btn-warning">edit</a>
    </div>


</div>

{% endblock %}

practice_article/templates/edit.html
{% extends 'base.html' %}


{% block body %}
<form action="{% url 'practice_article:update' id=article.id %}" class="mt-4" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">제목</label>
        <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">
    </div>

    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{article.content}}</textarea>

    </div>
    <input type="submit" class="btn btn-primary">
</form>

{% endblock %}

practice_article/templates/index.html
{% extends 'base.html' %}


{% block body %}

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>title</th>
            <th>link</th>
        </tr>
    </thead>
    <tbody>
        {% for article in practice_article %}
        <tr>
            <td>{{article.id}}</td>
            <td>{{article.title}}</td>
            <td>
                <a href="{% url 'practice_article:detail' id=article.id %}">detail</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>


</table>

{% endblock %}

practice_article/templates/new.html
{% extends 'base.html' %}


{% block body %}

<form action="{% url 'practice_article:create' %}" class="mt-4" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">title</label>
        <input type="text" class="form-control" id="title" name="title">
    </div>

    <div class="mb-3">
        <label for="content">content</label>
        <textarea name="content" id="content" class="form-control" cols="30" rows="10"></textarea>
    </div>

    <input type="submit" class="btn btn-primary">
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'practice_article:index' %}">Lunecid</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" href="{% url 'practice_article:new' %}">New</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
    </nav>



    <div class="container">

        {% block body %}

        {% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>